2022-03-11 17:01:40.843 INFO  [acme.Launcher@main] Starting Launcher using Java 1.8.0_281 on PC_ALVARO with PID 5892 (C:\Users\alvar\Desktop\Universidad\DP2\Workspace-22.0\Frameworks\Acme-Framework-22.1\target\classes started by alvar in C:\Users\alvar\Desktop\Universidad\DP2\Workspace-22.0\Projects\Acme-Toolkits) 
2022-03-11 17:01:40.844 DEBUG [acme.Launcher@main] Running with Spring Boot v2.4.2, Spring v5.3.3 
2022-03-11 17:01:40.845 INFO  [acme.Launcher@main] The following profiles are active: development,populator 
2022-03-11 17:01:43.841 DEBUG [org.apache.jasper.servlet.JasperInitializer@main] Initializing Jasper for context [application] 
2022-03-11 17:01:45.672 ERROR [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean@main] Failed to initialize JPA EntityManagerFactory: @OneToOne or @ManyToOne on acme.entities.component.Component.toolkit references an unknown entity: java.awt.Toolkit 
2022-03-11 17:01:45.673 WARN  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@main] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on acme.entities.component.Component.toolkit references an unknown entity: java.awt.Toolkit 
2022-03-11 17:01:45.737 ERROR [org.springframework.boot.SpringApplication@main] Application run failed at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788): Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on acme.entities.component.Component.toolkit references an unknown entity: java.awt.Toolkit\nat org.hibernate.cfg.ToOneFkSecondPass.doSecondPass(ToOneFkSecondPass.java:97): @OneToOne or @ManyToOne on acme.entities.component.Component.toolkit references an unknown entity: java.awt.Toolkit
2022-03-11 17:01:45.739 ERROR [acme.Launcher@main] org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788): Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on acme.entities.component.Component.toolkit references an unknown entity: java.awt.Toolkit\norg.hibernate.cfg.ToOneFkSecondPass.doSecondPass(ToOneFkSecondPass.java:97): @OneToOne or @ManyToOne on acme.entities.component.Component.toolkit references an unknown entity: java.awt.Toolkit 
2022-03-11 17:01:45.740 INFO  [acme.Launcher@main] The application log provides additional debugging messages! 
2022-03-11 17:01:46.751 DEBUG [acme.Launcher@main] Exit code = 1 
